// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const expireLots = `-- name: ExpireLots :execrows
update stock_lots set status = 'expired', updated_at = $1
where tenant_id = $2 and status = 'available' and expires_at <= $1
`

type ExpireLotsParams struct {
	Now      time.Time
	TenantID uuid.UUID
}

// Marks the available lots past their expiry at now (§12).
func (q *Queries) ExpireLots(ctx context.Context, arg ExpireLotsParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireLots, arg.Now, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLot = `-- name: GetLot :one
select l.id, l.ingredient_id, l.received_at, l.expires_at, l.status, l.source, l.procurement_item_id, l.note, l.created_at,
       coalesce((select sum(m.qty) from stock_movements m where m.tenant_id = l.tenant_id and m.lot_id = l.id), 0)::bigint as balance
from stock_lots l
where l.tenant_id = $1 and l.id = $2
`

type GetLotParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

type GetLotRow struct {
	ID                uuid.UUID
	IngredientID      uuid.UUID
	ReceivedAt        time.Time
	ExpiresAt         *time.Time
	Status            string
	Source            string
	ProcurementItemID *uuid.UUID
	Note              *string
	CreatedAt         time.Time
	Balance           int64
}

func (q *Queries) GetLot(ctx context.Context, arg GetLotParams) (GetLotRow, error) {
	row := q.db.QueryRow(ctx, getLot, arg.TenantID, arg.ID)
	var i GetLotRow
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.ReceivedAt,
		&i.ExpiresAt,
		&i.Status,
		&i.Source,
		&i.ProcurementItemID,
		&i.Note,
		&i.CreatedAt,
		&i.Balance,
	)
	return i, err
}

const insertCheck = `-- name: InsertCheck :exec
insert into stock_checks (tenant_id, lot_id, result, reason, note, checked_by, checked_at)
values ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertCheckParams struct {
	TenantID  uuid.UUID
	LotID     uuid.UUID
	Result    string
	Reason    *string
	Note      *string
	CheckedBy uuid.UUID
	Now       time.Time
}

func (q *Queries) InsertCheck(ctx context.Context, arg InsertCheckParams) error {
	_, err := q.db.Exec(ctx, insertCheck,
		arg.TenantID,
		arg.LotID,
		arg.Result,
		arg.Reason,
		arg.Note,
		arg.CheckedBy,
		arg.Now,
	)
	return err
}

const insertLot = `-- name: InsertLot :exec
insert into stock_lots (id, tenant_id, ingredient_id, received_at, expires_at, source, procurement_item_id, note,
                        created_by, created_at, updated_at)
values ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10, $10)
`

type InsertLotParams struct {
	ID                uuid.UUID
	TenantID          uuid.UUID
	IngredientID      uuid.UUID
	ReceivedAt        time.Time
	ExpiresAt         *time.Time
	Source            string
	ProcurementItemID *uuid.UUID
	Note              *string
	CreatedBy         uuid.UUID
	Now               time.Time
}

func (q *Queries) InsertLot(ctx context.Context, arg InsertLotParams) error {
	_, err := q.db.Exec(ctx, insertLot,
		arg.ID,
		arg.TenantID,
		arg.IngredientID,
		arg.ReceivedAt,
		arg.ExpiresAt,
		arg.Source,
		arg.ProcurementItemID,
		arg.Note,
		arg.CreatedBy,
		arg.Now,
	)
	return err
}

const insertMovement = `-- name: InsertMovement :exec
insert into stock_movements (tenant_id, lot_id, ingredient_id, kind, qty, batch_id, reason, actor_id, created_at)
values ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
`

type InsertMovementParams struct {
	TenantID     uuid.UUID
	LotID        uuid.UUID
	IngredientID uuid.UUID
	Kind         string
	Qty          int64
	BatchID      *uuid.UUID
	Reason       *string
	ActorID      uuid.UUID
	Now          time.Time
}

func (q *Queries) InsertMovement(ctx context.Context, arg InsertMovementParams) error {
	_, err := q.db.Exec(ctx, insertMovement,
		arg.TenantID,
		arg.LotID,
		arg.IngredientID,
		arg.Kind,
		arg.Qty,
		arg.BatchID,
		arg.Reason,
		arg.ActorID,
		arg.Now,
	)
	return err
}

const lastOKChecks = `-- name: LastOKChecks :many
select lot_id, max(checked_at)::timestamptz as checked_at
from stock_checks
where tenant_id = $1 and lot_id = any($2::uuid[]) and result = 'ok'
group by lot_id
`

type LastOKChecksParams struct {
	TenantID uuid.UUID
	LotIds   []uuid.UUID
}

type LastOKChecksRow struct {
	LotID     uuid.UUID
	CheckedAt time.Time
}

// The latest "masih bagus" check of each of the lots that have one.
func (q *Queries) LastOKChecks(ctx context.Context, arg LastOKChecksParams) ([]LastOKChecksRow, error) {
	rows, err := q.db.Query(ctx, lastOKChecks, arg.TenantID, arg.LotIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastOKChecksRow{}
	for rows.Next() {
		var i LastOKChecksRow
		if err := rows.Scan(&i.LotID, &i.CheckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIngredientStock = `-- name: LockIngredientStock :exec

select pg_advisory_xact_lock(hashtextextended('stock:' || $1::text, 0))
`

// Stock (M3.2). Every statement is scoped by tenant_id.
// Serializes the changes to one ingredient's stock until the transaction
// ends, so a balance read stays true while it is acted on.
func (q *Queries) LockIngredientStock(ctx context.Context, ingredientID string) error {
	_, err := q.db.Exec(ctx, lockIngredientStock, ingredientID)
	return err
}

const lots = `-- name: Lots :many
select l.id, l.ingredient_id, l.received_at, l.expires_at, l.status, l.source, l.procurement_item_id, l.note, l.created_at,
       coalesce((select sum(m.qty) from stock_movements m where m.tenant_id = l.tenant_id and m.lot_id = l.id), 0)::bigint as balance
from stock_lots l
where l.tenant_id = $1
  and (cardinality($2::uuid[]) = 0 or l.ingredient_id = any($2::uuid[]))
  and l.status = any($3::text[])
order by l.ingredient_id, l.received_at, l.id
`

type LotsParams struct {
	TenantID      uuid.UUID
	IngredientIds []uuid.UUID
	Statuses      []string
}

type LotsRow struct {
	ID                uuid.UUID
	IngredientID      uuid.UUID
	ReceivedAt        time.Time
	ExpiresAt         *time.Time
	Status            string
	Source            string
	ProcurementItemID *uuid.UUID
	Note              *string
	CreatedAt         time.Time
	Balance           int64
}

// The lots of the ingredients (every ingredient when none is given) in any
// of statuses, oldest first, each with its balance: the sum of its
// movements.
func (q *Queries) Lots(ctx context.Context, arg LotsParams) ([]LotsRow, error) {
	rows, err := q.db.Query(ctx, lots, arg.TenantID, arg.IngredientIds, arg.Statuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LotsRow{}
	for rows.Next() {
		var i LotsRow
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.ReceivedAt,
			&i.ExpiresAt,
			&i.Status,
			&i.Source,
			&i.ProcurementItemID,
			&i.Note,
			&i.CreatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLotStatus = `-- name: SetLotStatus :exec
update stock_lots set status = $1, updated_at = $2
where tenant_id = $3 and id = $4
`

type SetLotStatusParams struct {
	Status   string
	Now      time.Time
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) SetLotStatus(ctx context.Context, arg SetLotStatusParams) error {
	_, err := q.db.Exec(ctx, setLotStatus,
		arg.Status,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}
