// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ClosedDate struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	Date      pgtype.Date
	Reason    string
	CreatedAt time.Time
}

type ScheduleSetting struct {
	TenantID             uuid.UUID
	ShoppingBufferHours  int32
	DailyCapacityMinutes *int32
	PickupWindowStart    pgtype.Time
	PickupWindowEnd      pgtype.Time
	UpdatedAt            time.Time
}
