// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduling.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addClosedDate = `-- name: AddClosedDate :one
insert into closed_dates (tenant_id, date, reason, created_at)
values ($1, $2, $3, $4)
returning id, tenant_id, date, reason, created_at
`

type AddClosedDateParams struct {
	TenantID uuid.UUID
	Date     pgtype.Date
	Reason   string
	Now      time.Time
}

func (q *Queries) AddClosedDate(ctx context.Context, arg AddClosedDateParams) (ClosedDate, error) {
	row := q.db.QueryRow(ctx, addClosedDate,
		arg.TenantID,
		arg.Date,
		arg.Reason,
		arg.Now,
	)
	var i ClosedDate
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Date,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getScheduleSettings = `-- name: GetScheduleSettings :one

select tenant_id, shopping_buffer_hours, daily_capacity_minutes, pickup_window_start, pickup_window_end, updated_at from schedule_settings
where tenant_id = $1
`

// Scheduling settings and closed dates (M2.2). Every statement is scoped by
// tenant_id. Timestamps come from platform/clock.
func (q *Queries) GetScheduleSettings(ctx context.Context, tenantID uuid.UUID) (ScheduleSetting, error) {
	row := q.db.QueryRow(ctx, getScheduleSettings, tenantID)
	var i ScheduleSetting
	err := row.Scan(
		&i.TenantID,
		&i.ShoppingBufferHours,
		&i.DailyCapacityMinutes,
		&i.PickupWindowStart,
		&i.PickupWindowEnd,
		&i.UpdatedAt,
	)
	return i, err
}

const listClosedDates = `-- name: ListClosedDates :many
select id, tenant_id, date, reason, created_at from closed_dates
where tenant_id = $1
  and date between $2 and $3
order by date
`

type ListClosedDatesParams struct {
	TenantID uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

func (q *Queries) ListClosedDates(ctx context.Context, arg ListClosedDatesParams) ([]ClosedDate, error) {
	rows, err := q.db.Query(ctx, listClosedDates, arg.TenantID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClosedDate{}
	for rows.Next() {
		var i ClosedDate
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Date,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeClosedDate = `-- name: RemoveClosedDate :execrows
delete from closed_dates
where tenant_id = $1 and date = $2
`

type RemoveClosedDateParams struct {
	TenantID uuid.UUID
	Date     pgtype.Date
}

func (q *Queries) RemoveClosedDate(ctx context.Context, arg RemoveClosedDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeClosedDate, arg.TenantID, arg.Date)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertScheduleSettings = `-- name: UpsertScheduleSettings :one
insert into schedule_settings (tenant_id, shopping_buffer_hours, daily_capacity_minutes,
                               pickup_window_start, pickup_window_end, updated_at)
values ($1, $2, $3,
        $4, $5, $6)
on conflict (tenant_id) do update
set shopping_buffer_hours  = excluded.shopping_buffer_hours,
    daily_capacity_minutes = excluded.daily_capacity_minutes,
    pickup_window_start    = excluded.pickup_window_start,
    pickup_window_end      = excluded.pickup_window_end,
    updated_at             = excluded.updated_at
returning tenant_id, shopping_buffer_hours, daily_capacity_minutes, pickup_window_start, pickup_window_end, updated_at
`

type UpsertScheduleSettingsParams struct {
	TenantID             uuid.UUID
	ShoppingBufferHours  int32
	DailyCapacityMinutes *int32
	PickupWindowStart    pgtype.Time
	PickupWindowEnd      pgtype.Time
	Now                  time.Time
}

func (q *Queries) UpsertScheduleSettings(ctx context.Context, arg UpsertScheduleSettingsParams) (ScheduleSetting, error) {
	row := q.db.QueryRow(ctx, upsertScheduleSettings,
		arg.TenantID,
		arg.ShoppingBufferHours,
		arg.DailyCapacityMinutes,
		arg.PickupWindowStart,
		arg.PickupWindowEnd,
		arg.Now,
	)
	var i ScheduleSetting
	err := row.Scan(
		&i.TenantID,
		&i.ShoppingBufferHours,
		&i.DailyCapacityMinutes,
		&i.PickupWindowStart,
		&i.PickupWindowEnd,
		&i.UpdatedAt,
	)
	return i, err
}
