// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const componentsOfVariants = `-- name: ComponentsOfVariants :many
select variant_id, component_id, units_per_item
from variant_components
where tenant_id = $1
  and variant_id = any($2::uuid[])
order by variant_id, component_id
`

type ComponentsOfVariantsParams struct {
	TenantID   uuid.UUID
	VariantIds []uuid.UUID
}

type ComponentsOfVariantsRow struct {
	VariantID    uuid.UUID
	ComponentID  uuid.UUID
	UnitsPerItem float64
}

// Level 1 of batch aggregation (§11): the components each variant uses, per
// unit of the variant. Inactive variants are included on purpose: an order
// placed before a variant was switched off must still be produced. Ordered
// so recomputes are deterministic.
func (q *Queries) ComponentsOfVariants(ctx context.Context, arg ComponentsOfVariantsParams) ([]ComponentsOfVariantsRow, error) {
	rows, err := q.db.Query(ctx, componentsOfVariants, arg.TenantID, arg.VariantIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ComponentsOfVariantsRow{}
	for rows.Next() {
		var i ComponentsOfVariantsRow
		if err := rows.Scan(&i.VariantID, &i.ComponentID, &i.UnitsPerItem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const defaultPacks = `-- name: DefaultPacks :many
select ingredient_id, supplier_id, pack_size, pack_unit, price_idr
from ingredient_suppliers
where tenant_id = $1
  and is_default
  and ingredient_id = any($2::uuid[])
order by ingredient_id
`

type DefaultPacksParams struct {
	TenantID      uuid.UUID
	IngredientIds []uuid.UUID
}

type DefaultPacksRow struct {
	IngredientID uuid.UUID
	SupplierID   uuid.UUID
	PackSize     float64
	PackUnit     string
	PriceIdr     *int64
}

// Level 3 of batch aggregation (§11): the default supplier and pack per
// ingredient. pack_size is in the ingredient's base unit.
func (q *Queries) DefaultPacks(ctx context.Context, arg DefaultPacksParams) ([]DefaultPacksRow, error) {
	rows, err := q.db.Query(ctx, defaultPacks, arg.TenantID, arg.IngredientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DefaultPacksRow{}
	for rows.Next() {
		var i DefaultPacksRow
		if err := rows.Scan(
			&i.IngredientID,
			&i.SupplierID,
			&i.PackSize,
			&i.PackUnit,
			&i.PriceIdr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ingredientsOfComponents = `-- name: IngredientsOfComponents :many
select ci.component_id,
       ci.ingredient_id,
       ci.model_type,
       ci.params,
       ci.waste_factor,
       ci.version,
       i.base_unit
from component_ingredients ci
join ingredients i on i.tenant_id = ci.tenant_id and i.id = ci.ingredient_id
where ci.tenant_id = $1
  and ci.component_id = any($2::uuid[])
order by ci.component_id, ci.ingredient_id
`

type IngredientsOfComponentsParams struct {
	TenantID     uuid.UUID
	ComponentIds []uuid.UUID
}

type IngredientsOfComponentsRow struct {
	ComponentID  uuid.UUID
	IngredientID uuid.UUID
	ModelType    string
	Params       []byte
	WasteFactor  float64
	Version      int32
	BaseUnit     string
}

// Level 2 of batch aggregation (§11): each component's recipe lines with
// what the recipe engine and the rounding rule need.
func (q *Queries) IngredientsOfComponents(ctx context.Context, arg IngredientsOfComponentsParams) ([]IngredientsOfComponentsRow, error) {
	rows, err := q.db.Query(ctx, ingredientsOfComponents, arg.TenantID, arg.ComponentIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IngredientsOfComponentsRow{}
	for rows.Next() {
		var i IngredientsOfComponentsRow
		if err := rows.Scan(
			&i.ComponentID,
			&i.IngredientID,
			&i.ModelType,
			&i.Params,
			&i.WasteFactor,
			&i.Version,
			&i.BaseUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
