// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aggregation.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProcured = `-- name: AddProcured :execrows
update batch_requirements
set qty_ordered = qty_ordered + $1, qty_received = qty_received + $2,
    status = case when qty_ordered + $1 > 0 then 'ordered'
                  when qty_received + $2 > 0 then 'received'
                  else 'needed' end,
    updated_at = $3
where tenant_id = $4 and batch_id = $5 and ingredient_id = $6
`

type AddProcuredParams struct {
	Ordered      int64
	Received     int64
	Now          time.Time
	TenantID     uuid.UUID
	BatchID      uuid.UUID
	IngredientID uuid.UUID
}

// Procurement's side of a line (M4): what was ordered and has not arrived
// yet, and what arrived; the status follows from them.
func (q *Queries) AddProcured(ctx context.Context, arg AddProcuredParams) (int64, error) {
	result, err := q.db.Exec(ctx, addProcured,
		arg.Ordered,
		arg.Received,
		arg.Now,
		arg.TenantID,
		arg.BatchID,
		arg.IngredientID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const batchComponentTotals = `-- name: BatchComponentTotals :many
select tenant_id, batch_id, component_id, units from batch_component_totals
where tenant_id = $1 and batch_id = $2
order by component_id
`

type BatchComponentTotalsParams struct {
	TenantID uuid.UUID
	BatchID  uuid.UUID
}

func (q *Queries) BatchComponentTotals(ctx context.Context, arg BatchComponentTotalsParams) ([]BatchComponentTotal, error) {
	rows, err := q.db.Query(ctx, batchComponentTotals, arg.TenantID, arg.BatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchComponentTotal{}
	for rows.Next() {
		var i BatchComponentTotal
		if err := rows.Scan(
			&i.TenantID,
			&i.BatchID,
			&i.ComponentID,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchRequirements = `-- name: BatchRequirements :many
select tenant_id, batch_id, ingredient_id, qty_needed, qty_usable_stock, qty_ordered, qty_to_buy, supplier_id, pack_size, pack_unit, pack_price_idr, packs_to_buy, status, updated_at, qty_received from batch_requirements
where tenant_id = $1 and batch_id = $2
order by ingredient_id
`

type BatchRequirementsParams struct {
	TenantID uuid.UUID
	BatchID  uuid.UUID
}

func (q *Queries) BatchRequirements(ctx context.Context, arg BatchRequirementsParams) ([]BatchRequirement, error) {
	rows, err := q.db.Query(ctx, batchRequirements, arg.TenantID, arg.BatchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchRequirement{}
	for rows.Next() {
		var i BatchRequirement
		if err := rows.Scan(
			&i.TenantID,
			&i.BatchID,
			&i.IngredientID,
			&i.QtyNeeded,
			&i.QtyUsableStock,
			&i.QtyOrdered,
			&i.QtyToBuy,
			&i.SupplierID,
			&i.PackSize,
			&i.PackUnit,
			&i.PackPriceIdr,
			&i.PacksToBuy,
			&i.Status,
			&i.UpdatedAt,
			&i.QtyReceived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimedBefore = `-- name: ClaimedBefore :many
select r.ingredient_id, sum(r.qty_usable_stock)::bigint as claimed
from batch_requirements r
join production_batches b on b.tenant_id = r.tenant_id and b.id = r.batch_id
where r.tenant_id = $1 and b.batch_date < $2 and b.status <> 'done'
  and r.ingredient_id = any($3::uuid[]) and r.qty_usable_stock > 0
group by r.ingredient_id
`

type ClaimedBeforeParams struct {
	TenantID      uuid.UUID
	BatchDate     pgtype.Date
	IngredientIds []uuid.UUID
}

type ClaimedBeforeRow struct {
	IngredientID uuid.UUID
	Claimed      int64
}

// The stock the batches before a date count on, per ingredient: a batch
// only gets what they left (§11, allocated by date). Done batches have
// consumed theirs (M3.3) and claim nothing.
func (q *Queries) ClaimedBefore(ctx context.Context, arg ClaimedBeforeParams) ([]ClaimedBeforeRow, error) {
	rows, err := q.db.Query(ctx, claimedBefore, arg.TenantID, arg.BatchDate, arg.IngredientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimedBeforeRow{}
	for rows.Next() {
		var i ClaimedBeforeRow
		if err := rows.Scan(&i.IngredientID, &i.Claimed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteComponentTotals = `-- name: DeleteComponentTotals :exec
delete from batch_component_totals
where tenant_id = $1 and batch_id = $2
`

type DeleteComponentTotalsParams struct {
	TenantID uuid.UUID
	BatchID  uuid.UUID
}

func (q *Queries) DeleteComponentTotals(ctx context.Context, arg DeleteComponentTotalsParams) error {
	_, err := q.db.Exec(ctx, deleteComponentTotals, arg.TenantID, arg.BatchID)
	return err
}

const deleteStaleRequirements = `-- name: DeleteStaleRequirements :exec
delete from batch_requirements
where tenant_id = $1 and batch_id = $2 and status = 'needed'
  and not (ingredient_id = any($3::uuid[]))
`

type DeleteStaleRequirementsParams struct {
	TenantID uuid.UUID
	BatchID  uuid.UUID
	Keep     []uuid.UUID
}

// Drops the ingredients no longer needed that nobody has ordered yet.
func (q *Queries) DeleteStaleRequirements(ctx context.Context, arg DeleteStaleRequirementsParams) error {
	_, err := q.db.Exec(ctx, deleteStaleRequirements, arg.TenantID, arg.BatchID, arg.Keep)
	return err
}

const ensureBatch = `-- name: EnsureBatch :exec

insert into production_batches (tenant_id, batch_date, created_at, updated_at)
values ($1, $2, $3, $3)
on conflict (tenant_id, batch_date) do nothing
`

type EnsureBatchParams struct {
	TenantID  uuid.UUID
	BatchDate pgtype.Date
	Now       time.Time
}

// Batch aggregation (M3.1). Every statement is scoped by tenant_id.
func (q *Queries) EnsureBatch(ctx context.Context, arg EnsureBatchParams) error {
	_, err := q.db.Exec(ctx, ensureBatch, arg.TenantID, arg.BatchDate, arg.Now)
	return err
}

const getBatch = `-- name: GetBatch :one
select id, tenant_id, batch_date, status, computed_at, error, created_at, updated_at from production_batches
where tenant_id = $1 and batch_date = $2
`

type GetBatchParams struct {
	TenantID  uuid.UUID
	BatchDate pgtype.Date
}

func (q *Queries) GetBatch(ctx context.Context, arg GetBatchParams) (ProductionBatch, error) {
	row := q.db.QueryRow(ctx, getBatch, arg.TenantID, arg.BatchDate)
	var i ProductionBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchDate,
		&i.Status,
		&i.ComputedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertComponentTotal = `-- name: InsertComponentTotal :exec
insert into batch_component_totals (tenant_id, batch_id, component_id, units)
values ($1, $2, $3, $4)
`

type InsertComponentTotalParams struct {
	TenantID    uuid.UUID
	BatchID     uuid.UUID
	ComponentID uuid.UUID
	Units       float64
}

func (q *Queries) InsertComponentTotal(ctx context.Context, arg InsertComponentTotalParams) error {
	_, err := q.db.Exec(ctx, insertComponentTotal,
		arg.TenantID,
		arg.BatchID,
		arg.ComponentID,
		arg.Units,
	)
	return err
}

const listBatches = `-- name: ListBatches :many
select b.id, b.batch_date, b.status, b.computed_at, b.error,
       (select count(*) from batch_requirements r where r.batch_id = b.id and r.qty_to_buy > 0)::int as items_to_buy,
       (select coalesce(sum(r.packs_to_buy * r.pack_price_idr), 0) from batch_requirements r where r.batch_id = b.id)::bigint as cost_idr
from production_batches b
where b.tenant_id = $1 and b.batch_date between $2 and $3
order by b.batch_date
`

type ListBatchesParams struct {
	TenantID uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type ListBatchesRow struct {
	ID         uuid.UUID
	BatchDate  pgtype.Date
	Status     string
	ComputedAt *time.Time
	Error      *string
	ItemsToBuy int32
	CostIdr    int64
}

func (q *Queries) ListBatches(ctx context.Context, arg ListBatchesParams) ([]ListBatchesRow, error) {
	rows, err := q.db.Query(ctx, listBatches, arg.TenantID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBatchesRow{}
	for rows.Next() {
		var i ListBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BatchDate,
			&i.Status,
			&i.ComputedAt,
			&i.Error,
			&i.ItemsToBuy,
			&i.CostIdr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBatch = `-- name: LockBatch :one
select id, tenant_id, batch_date, status, computed_at, error, created_at, updated_at from production_batches
where tenant_id = $1 and batch_date = $2
for update
`

type LockBatchParams struct {
	TenantID  uuid.UUID
	BatchDate pgtype.Date
}

// A computation holds its batch's row until the transaction ends, so two
// computations of one batch take turns and the last one wins whole.
func (q *Queries) LockBatch(ctx context.Context, arg LockBatchParams) (ProductionBatch, error) {
	row := q.db.QueryRow(ctx, lockBatch, arg.TenantID, arg.BatchDate)
	var i ProductionBatch
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchDate,
		&i.Status,
		&i.ComputedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBatchComputed = `-- name: MarkBatchComputed :exec
update production_batches
set computed_at = $1, error = null, updated_at = $1
where tenant_id = $2 and id = $3
`

type MarkBatchComputedParams struct {
	Now      *time.Time
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) MarkBatchComputed(ctx context.Context, arg MarkBatchComputedParams) error {
	_, err := q.db.Exec(ctx, markBatchComputed, arg.Now, arg.TenantID, arg.ID)
	return err
}

const markBatchFailed = `-- name: MarkBatchFailed :exec
insert into production_batches (tenant_id, batch_date, error, created_at, updated_at)
values ($1, $2, $3, $4, $4)
on conflict (tenant_id, batch_date) do update set error = excluded.error, updated_at = excluded.updated_at
`

type MarkBatchFailedParams struct {
	TenantID  uuid.UUID
	BatchDate pgtype.Date
	Error     *string
	Now       time.Time
}

// Runs after the failed computation rolled back, so the batch may not exist yet.
func (q *Queries) MarkBatchFailed(ctx context.Context, arg MarkBatchFailedParams) error {
	_, err := q.db.Exec(ctx, markBatchFailed,
		arg.TenantID,
		arg.BatchDate,
		arg.Error,
		arg.Now,
	)
	return err
}

const openBatchDates = `-- name: OpenBatchDates :many
select batch_date from production_batches
where tenant_id = $1 and status = 'open'
order by batch_date
`

func (q *Queries) OpenBatchDates(ctx context.Context, tenantID uuid.UUID) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, openBatchDates, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var batch_date pgtype.Date
		if err := rows.Scan(&batch_date); err != nil {
			return nil, err
		}
		items = append(items, batch_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBatchStatus = `-- name: SetBatchStatus :execrows
update production_batches set status = $1, updated_at = $2
where tenant_id = $3 and batch_date = $4
  and status = any($5::text[])
`

type SetBatchStatusParams struct {
	Status       string
	Now          time.Time
	TenantID     uuid.UUID
	BatchDate    pgtype.Date
	FromStatuses []string
}

// Moves a batch on, only from one of the statuses given: a step already
// taken, or one out of order, changes nothing.
func (q *Queries) SetBatchStatus(ctx context.Context, arg SetBatchStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBatchStatus,
		arg.Status,
		arg.Now,
		arg.TenantID,
		arg.BatchDate,
		arg.FromStatuses,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upcomingBatchDates = `-- name: UpcomingBatchDates :many
select batch_date from production_batches
where tenant_id = $1 and batch_date >= $2 and status <> 'done'
order by batch_date
`

type UpcomingBatchDatesParams struct {
	TenantID uuid.UUID
	FromDate pgtype.Date
}

// The batches still to be made from a date on: what a recipe change affects.
func (q *Queries) UpcomingBatchDates(ctx context.Context, arg UpcomingBatchDatesParams) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, upcomingBatchDates, arg.TenantID, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var batch_date pgtype.Date
		if err := rows.Scan(&batch_date); err != nil {
			return nil, err
		}
		items = append(items, batch_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRequirement = `-- name: UpsertRequirement :exec
insert into batch_requirements (tenant_id, batch_id, ingredient_id, qty_needed, qty_usable_stock, qty_to_buy,
                                supplier_id, pack_size, pack_unit, pack_price_idr, packs_to_buy, updated_at)
values ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10,
        $11, $12)
on conflict (batch_id, ingredient_id) do update
set qty_needed = excluded.qty_needed, qty_usable_stock = excluded.qty_usable_stock, qty_to_buy = excluded.qty_to_buy,
    supplier_id = excluded.supplier_id, pack_size = excluded.pack_size, pack_unit = excluded.pack_unit,
    pack_price_idr = excluded.pack_price_idr, packs_to_buy = excluded.packs_to_buy, updated_at = excluded.updated_at
`

type UpsertRequirementParams struct {
	TenantID       uuid.UUID
	BatchID        uuid.UUID
	IngredientID   uuid.UUID
	QtyNeeded      int64
	QtyUsableStock int64
	QtyToBuy       int64
	SupplierID     *uuid.UUID
	PackSize       *float64
	PackUnit       *string
	PackPriceIdr   *int64
	PacksToBuy     *int64
	Now            time.Time
}

// A computation sets what is needed and what to buy; what was ordered and
// the row's status belong to procurement (M4) and are left as they are.
func (q *Queries) UpsertRequirement(ctx context.Context, arg UpsertRequirementParams) error {
	_, err := q.db.Exec(ctx, upsertRequirement,
		arg.TenantID,
		arg.BatchID,
		arg.IngredientID,
		arg.QtyNeeded,
		arg.QtyUsableStock,
		arg.QtyToBuy,
		arg.SupplierID,
		arg.PackSize,
		arg.PackUnit,
		arg.PackPriceIdr,
		arg.PacksToBuy,
		arg.Now,
	)
	return err
}
