// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BatchComponentTotal struct {
	TenantID    uuid.UUID
	BatchID     uuid.UUID
	ComponentID uuid.UUID
	Units       float64
}

type BatchRequirement struct {
	TenantID       uuid.UUID
	BatchID        uuid.UUID
	IngredientID   uuid.UUID
	QtyNeeded      int64
	QtyUsableStock int64
	QtyOrdered     int64
	QtyToBuy       int64
	SupplierID     *uuid.UUID
	PackSize       *float64
	PackUnit       *string
	PackPriceIdr   *int64
	PacksToBuy     *int64
	Status         string
	UpdatedAt      time.Time
	QtyReceived    int64
}

type ProductionBatch struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	BatchDate  pgtype.Date
	Status     string
	ComputedAt *time.Time
	Error      *string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
