// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
insert into customers (tenant_id, auth_user_id, name, email, phone, created_at)
values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
returning id, tenant_id, auth_user_id, name, email, phone, created_at
`

type CreateCustomerParams struct {
	TenantID   uuid.UUID
	AuthUserID *uuid.UUID
	Name       string
	Email      *string
	Phone      *string
	CreatedAt  time.Time
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.TenantID,
		arg.AuthUserID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.CreatedAt,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomerByAuthUser = `-- name: GetCustomerByAuthUser :one
select id, tenant_id, auth_user_id, name, email, phone, created_at
from customers
where tenant_id = $1
  and auth_user_id = $2::uuid
`

type GetCustomerByAuthUserParams struct {
	TenantID   uuid.UUID
	AuthUserID uuid.UUID
}

func (q *Queries) GetCustomerByAuthUser(ctx context.Context, arg GetCustomerByAuthUserParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByAuthUser, arg.TenantID, arg.AuthUserID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.AuthUserID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.CreatedAt,
	)
	return i, err
}

const grantStaffRole = `-- name: GrantStaffRole :exec
insert into staff_roles (tenant_id, auth_user_id, role, created_at)
values ($1, $2, $3, $4)
on conflict (tenant_id, auth_user_id, role) do nothing
`

type GrantStaffRoleParams struct {
	TenantID   uuid.UUID
	AuthUserID uuid.UUID
	Role       string
	CreatedAt  time.Time
}

func (q *Queries) GrantStaffRole(ctx context.Context, arg GrantStaffRoleParams) error {
	_, err := q.db.Exec(ctx, grantStaffRole,
		arg.TenantID,
		arg.AuthUserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const listStaffRoles = `-- name: ListStaffRoles :many
select role
from staff_roles
where tenant_id = $1
  and auth_user_id = $2
order by role
`

type ListStaffRolesParams struct {
	TenantID   uuid.UUID
	AuthUserID uuid.UUID
}

func (q *Queries) ListStaffRoles(ctx context.Context, arg ListStaffRolesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaffRoles, arg.TenantID, arg.AuthUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role string
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenants = `-- name: ListTenants :many
select id, name, created_at
from tenants
order by created_at, id
limit $1
`

// Single-tenant mode resolves its tenant by listing at most a few rows. This is
// the only identity query not scoped by tenant_id.
func (q *Queries) ListTenants(ctx context.Context, maxRows int32) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCustomer = `-- name: UpsertCustomer :one
insert into customers (tenant_id, auth_user_id, name, email, phone, created_at)
values ($1, $2, $3, $4, $5, $6)
on conflict (tenant_id, auth_user_id) where auth_user_id is not null
do update set name = excluded.name, email = excluded.email, phone = excluded.phone
returning id, name, email, phone
`

type UpsertCustomerParams struct {
	TenantID   uuid.UUID
	AuthUserID *uuid.UUID
	Name       string
	Email      *string
	Phone      *string
	CreatedAt  time.Time
}

type UpsertCustomerRow struct {
	ID    uuid.UUID
	Name  string
	Email *string
	Phone *string
}

// A signed-in customer has one record per tenant. The phone comes from the
// verified token; the name and email from the latest checkout.
func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (UpsertCustomerRow, error) {
	row := q.db.QueryRow(ctx, upsertCustomer,
		arg.TenantID,
		arg.AuthUserID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.CreatedAt,
	)
	var i UpsertCustomerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
	)
	return i, err
}
