// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID         uuid.UUID
	TenantID   uuid.UUID
	AuthUserID *uuid.UUID
	Name       string
	Email      *string
	Phone      *string
	CreatedAt  time.Time
}

type Tenant struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
}
