// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type PaymentPolicy struct {
	TenantID               uuid.UUID
	DpMinPercent           int32
	DpCoversIngredientCost bool
	BalanceDueHoursBefore  int32
	DpInvoiceValidMinutes  int32
	UpdatedAt              time.Time
}
