// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
)

type Payment struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	OrderID     uuid.UUID
	Kind        string
	Provider    string
	ExternalID  *string
	AmountIdr   int64
	FeeIdr      int64
	Status      string
	ExpiresAt   *time.Time
	PaidAt      *time.Time
	Raw         []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CheckoutUrl *string
}

type PaymentPolicy struct {
	TenantID               uuid.UUID
	DpMinPercent           int32
	DpCoversIngredientCost bool
	BalanceDueHoursBefore  int32
	DpInvoiceValidMinutes  int32
	UpdatedAt              time.Time
}
