// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addPayment = `-- name: AddPayment :exec
insert into payments (id, tenant_id, order_id, kind, provider, method, amount_idr, fee_idr, status,
                      expires_at, created_at, updated_at)
values ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11, $11)
`

type AddPaymentParams struct {
	ID        uuid.UUID
	TenantID  uuid.UUID
	OrderID   uuid.UUID
	Kind      string
	Provider  string
	Method    *string
	AmountIdr int64
	FeeIdr    int64
	Status    string
	ExpiresAt *time.Time
	Now       time.Time
}

func (q *Queries) AddPayment(ctx context.Context, arg AddPaymentParams) error {
	_, err := q.db.Exec(ctx, addPayment,
		arg.ID,
		arg.TenantID,
		arg.OrderID,
		arg.Kind,
		arg.Provider,
		arg.Method,
		arg.AmountIdr,
		arg.FeeIdr,
		arg.Status,
		arg.ExpiresAt,
		arg.Now,
	)
	return err
}

const getPaymentPolicy = `-- name: GetPaymentPolicy :one

select tenant_id, dp_min_percent, dp_covers_ingredient_cost, balance_due_hours_before, dp_invoice_valid_minutes, updated_at, dp_min_total_idr, min_order_idr from payment_policies
where tenant_id = $1
`

// Payment policies and the payment ledger (M2.3). Every statement is scoped
// by tenant_id.
func (q *Queries) GetPaymentPolicy(ctx context.Context, tenantID uuid.UUID) (PaymentPolicy, error) {
	row := q.db.QueryRow(ctx, getPaymentPolicy, tenantID)
	var i PaymentPolicy
	err := row.Scan(
		&i.TenantID,
		&i.DpMinPercent,
		&i.DpCoversIngredientCost,
		&i.BalanceDueHoursBefore,
		&i.DpInvoiceValidMinutes,
		&i.UpdatedAt,
		&i.DpMinTotalIdr,
		&i.MinOrderIdr,
	)
	return i, err
}

const listPaymentMethodFees = `-- name: ListPaymentMethodFees :many
select tenant_id, method, fixed_idr, rate_bps, vat_included, enabled, updated_at from payment_method_fees
where tenant_id = $1
order by method
`

func (q *Queries) ListPaymentMethodFees(ctx context.Context, tenantID uuid.UUID) ([]PaymentMethodFee, error) {
	rows, err := q.db.Query(ctx, listPaymentMethodFees, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentMethodFee{}
	for rows.Next() {
		var i PaymentMethodFee
		if err := rows.Scan(
			&i.TenantID,
			&i.Method,
			&i.FixedIdr,
			&i.RateBps,
			&i.VatIncluded,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderPayments = `-- name: OrderPayments :many
select id, tenant_id, order_id, kind, provider, external_id, amount_idr, fee_idr, status, expires_at, paid_at, raw, created_at, updated_at, checkout_url, method from payments
where tenant_id = $1 and order_id = $2
order by created_at, id
`

type OrderPaymentsParams struct {
	TenantID uuid.UUID
	OrderID  uuid.UUID
}

func (q *Queries) OrderPayments(ctx context.Context, arg OrderPaymentsParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, orderPayments, arg.TenantID, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.Kind,
			&i.Provider,
			&i.ExternalID,
			&i.AmountIdr,
			&i.FeeIdr,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.Raw,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CheckoutUrl,
			&i.Method,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPaymentInvoice = `-- name: SetPaymentInvoice :execrows
update payments
set external_id = $1, checkout_url = $2, updated_at = $3
where tenant_id = $4 and id = $5 and status = 'pending'
`

type SetPaymentInvoiceParams struct {
	ExternalID  *string
	CheckoutUrl *string
	Now         time.Time
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetPaymentInvoice(ctx context.Context, arg SetPaymentInvoiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPaymentInvoice,
		arg.ExternalID,
		arg.CheckoutUrl,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
