// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ProcurementOrder struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	BatchID     uuid.UUID
	BatchDate   pgtype.Date
	SupplierID  *uuid.UUID
	AdapterKey  string
	ExternalRef *string
	Status      string
	Note        *string
	CreatedBy   uuid.UUID
	SentAt      *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProcurementOrderItem struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OrderID      uuid.UUID
	IngredientID uuid.UUID
	Qty          int64
	Packs        *int64
	PackSize     *float64
	PackUnit     *string
	PackPriceIdr *int64
	Status       string
	QtyReceived  *int64
	ReceivedAt   *time.Time
}
