// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procurement.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrder = `-- name: GetOrder :one
select id, tenant_id, batch_id, batch_date, supplier_id, adapter_key, external_ref, status, note, created_by, sent_at, created_at, updated_at from procurement_orders
where tenant_id = $1 and id = $2
`

type GetOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (ProcurementOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.TenantID, arg.ID)
	var i ProcurementOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchID,
		&i.BatchDate,
		&i.SupplierID,
		&i.AdapterKey,
		&i.ExternalRef,
		&i.Status,
		&i.Note,
		&i.CreatedBy,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertItem = `-- name: InsertItem :exec
insert into procurement_order_items (id, tenant_id, order_id, ingredient_id, qty, packs, pack_size, pack_unit, pack_price_idr)
values ($1, $2, $3, $4, $5, $6,
        $7, $8, $9)
`

type InsertItemParams struct {
	ID           uuid.UUID
	TenantID     uuid.UUID
	OrderID      uuid.UUID
	IngredientID uuid.UUID
	Qty          int64
	Packs        *int64
	PackSize     *float64
	PackUnit     *string
	PackPriceIdr *int64
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.Exec(ctx, insertItem,
		arg.ID,
		arg.TenantID,
		arg.OrderID,
		arg.IngredientID,
		arg.Qty,
		arg.Packs,
		arg.PackSize,
		arg.PackUnit,
		arg.PackPriceIdr,
	)
	return err
}

const insertOrder = `-- name: InsertOrder :exec

insert into procurement_orders (id, tenant_id, batch_id, batch_date, supplier_id, adapter_key, external_ref, status, note,
                                created_by, created_at, updated_at)
values ($1, $2, $3, $4, $5,
        $6, $7, 'ordered', $8, $9, $10, $10)
`

type InsertOrderParams struct {
	ID          uuid.UUID
	TenantID    uuid.UUID
	BatchID     uuid.UUID
	BatchDate   pgtype.Date
	SupplierID  *uuid.UUID
	AdapterKey  string
	ExternalRef *string
	Note        *string
	CreatedBy   uuid.UUID
	Now         time.Time
}

// Procurement (M4.1). Every statement is scoped by tenant_id.
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.TenantID,
		arg.BatchID,
		arg.BatchDate,
		arg.SupplierID,
		arg.AdapterKey,
		arg.ExternalRef,
		arg.Note,
		arg.CreatedBy,
		arg.Now,
	)
	return err
}

const listOrders = `-- name: ListOrders :many
select id, tenant_id, batch_id, batch_date, supplier_id, adapter_key, external_ref, status, note, created_by, sent_at, created_at, updated_at from procurement_orders
where tenant_id = $1 and batch_date = $2
order by created_at, id
`

type ListOrdersParams struct {
	TenantID  uuid.UUID
	BatchDate pgtype.Date
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]ProcurementOrder, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.TenantID, arg.BatchDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementOrder{}
	for rows.Next() {
		var i ProcurementOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.BatchID,
			&i.BatchDate,
			&i.SupplierID,
			&i.AdapterKey,
			&i.ExternalRef,
			&i.Status,
			&i.Note,
			&i.CreatedBy,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOrder = `-- name: LockOrder :one
select id, tenant_id, batch_id, batch_date, supplier_id, adapter_key, external_ref, status, note, created_by, sent_at, created_at, updated_at from procurement_orders
where tenant_id = $1 and id = $2
for update
`

type LockOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

// A change to an order holds its row until the transaction ends.
func (q *Queries) LockOrder(ctx context.Context, arg LockOrderParams) (ProcurementOrder, error) {
	row := q.db.QueryRow(ctx, lockOrder, arg.TenantID, arg.ID)
	var i ProcurementOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.BatchID,
		&i.BatchDate,
		&i.SupplierID,
		&i.AdapterKey,
		&i.ExternalRef,
		&i.Status,
		&i.Note,
		&i.CreatedBy,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const orderItems = `-- name: OrderItems :many
select id, tenant_id, order_id, ingredient_id, qty, packs, pack_size, pack_unit, pack_price_idr, status, qty_received, received_at from procurement_order_items
where tenant_id = $1 and order_id = any($2::uuid[])
order by order_id, ingredient_id
`

type OrderItemsParams struct {
	TenantID uuid.UUID
	OrderIds []uuid.UUID
}

func (q *Queries) OrderItems(ctx context.Context, arg OrderItemsParams) ([]ProcurementOrderItem, error) {
	rows, err := q.db.Query(ctx, orderItems, arg.TenantID, arg.OrderIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcurementOrderItem{}
	for rows.Next() {
		var i ProcurementOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.IngredientID,
			&i.Qty,
			&i.Packs,
			&i.PackSize,
			&i.PackUnit,
			&i.PackPriceIdr,
			&i.Status,
			&i.QtyReceived,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setItemCancelled = `-- name: SetItemCancelled :execrows
update procurement_order_items set status = 'cancelled'
where tenant_id = $1 and id = $2 and status = 'ordered'
`

type SetItemCancelledParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) SetItemCancelled(ctx context.Context, arg SetItemCancelledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemCancelled, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setItemReceived = `-- name: SetItemReceived :execrows
update procurement_order_items
set status = 'received', qty_received = $1, received_at = $2
where tenant_id = $3 and id = $4 and status = 'ordered'
`

type SetItemReceivedParams struct {
	QtyReceived *int64
	ReceivedAt  *time.Time
	TenantID    uuid.UUID
	ID          uuid.UUID
}

func (q *Queries) SetItemReceived(ctx context.Context, arg SetItemReceivedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setItemReceived,
		arg.QtyReceived,
		arg.ReceivedAt,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOrderStatus = `-- name: SetOrderStatus :exec
update procurement_orders set status = $1, updated_at = $2
where tenant_id = $3 and id = $4
`

type SetOrderStatusParams struct {
	Status   string
	Now      time.Time
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus,
		arg.Status,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}
