// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchCutoffs = `-- name: BatchCutoffs :many

select production_date, min(shopping_cutoff_at)::timestamptz as cutoff
from orders
where tenant_id = $1
  and production_date between $2 and $3
  and status = any($4::text[])
group by production_date
order by production_date
`

type BatchCutoffsParams struct {
	TenantID uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
	Statuses []string
}

type BatchCutoffsRow struct {
	ProductionDate pgtype.Date
	Cutoff         time.Time
}

// Orders (M2.3). Every statement is scoped by tenant_id.
// The shopping cutoff of each production date from..to: the earliest own
// cutoff among the orders counting for production (§15). The statuses come
// from orders.Status.CountsForProduction, so the rule lives in one place.
func (q *Queries) BatchCutoffs(ctx context.Context, arg BatchCutoffsParams) ([]BatchCutoffsRow, error) {
	rows, err := q.db.Query(ctx, batchCutoffs,
		arg.TenantID,
		arg.FromDate,
		arg.ToDate,
		arg.Statuses,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchCutoffsRow{}
	for rows.Next() {
		var i BatchCutoffsRow
		if err := rows.Scan(&i.ProductionDate, &i.Cutoff); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
