// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeOrderDays = `-- name: ActiveOrderDays :many
select id, production_date, (pickup_at at time zone 'Asia/Jakarta')::date as pickup_date
from orders
where tenant_id = $1
  and status = any($2::text[])
  and (production_date between $3 and $4
       or (pickup_at at time zone 'Asia/Jakarta')::date between $3 and $4)
`

type ActiveOrderDaysParams struct {
	TenantID uuid.UUID
	Statuses []string
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type ActiveOrderDaysRow struct {
	ID             uuid.UUID
	ProductionDate pgtype.Date
	PickupDate     pgtype.Date
}

// The production and pickup days (Asia/Jakarta) of the orders in statuses
// that touch from..to: what keeps a closed day on hold (§15).
func (q *Queries) ActiveOrderDays(ctx context.Context, arg ActiveOrderDaysParams) ([]ActiveOrderDaysRow, error) {
	rows, err := q.db.Query(ctx, activeOrderDays,
		arg.TenantID,
		arg.Statuses,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveOrderDaysRow{}
	for rows.Next() {
		var i ActiveOrderDaysRow
		if err := rows.Scan(&i.ID, &i.ProductionDate, &i.PickupDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const batchCutoffs = `-- name: BatchCutoffs :many

select production_date, min(shopping_cutoff_at)::timestamptz as cutoff
from orders
where tenant_id = $1
  and production_date between $2 and $3
  and status = any($4::text[])
group by production_date
order by production_date
`

type BatchCutoffsParams struct {
	TenantID uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
	Statuses []string
}

type BatchCutoffsRow struct {
	ProductionDate pgtype.Date
	Cutoff         time.Time
}

// Orders (M2.3). Every statement is scoped by tenant_id.
// The shopping cutoff of each production date from..to: the earliest own
// cutoff among the orders counting for production (§15). The statuses come
// from orders.Status.CountsForProduction, so the rule lives in one place.
func (q *Queries) BatchCutoffs(ctx context.Context, arg BatchCutoffsParams) ([]BatchCutoffsRow, error) {
	rows, err := q.db.Query(ctx, batchCutoffs,
		arg.TenantID,
		arg.FromDate,
		arg.ToDate,
		arg.Statuses,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchCutoffsRow{}
	for rows.Next() {
		var i BatchCutoffsRow
		if err := rows.Scan(&i.ProductionDate, &i.Cutoff); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCustomerOrders = `-- name: CountCustomerOrders :one
select count(*)::int from orders
where tenant_id = $1 and customer_id = $2 and status = $3
`

type CountCustomerOrdersParams struct {
	TenantID   uuid.UUID
	CustomerID uuid.UUID
	Status     string
}

func (q *Queries) CountCustomerOrders(ctx context.Context, arg CountCustomerOrdersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countCustomerOrders, arg.TenantID, arg.CustomerID, arg.Status)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const findOrderByIdempotencyKey = `-- name: FindOrderByIdempotencyKey :one
select id from orders
where tenant_id = $1 and customer_id = $2
  and idempotency_key = $3
`

type FindOrderByIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	CustomerID     uuid.UUID
	IdempotencyKey uuid.UUID
}

func (q *Queries) FindOrderByIdempotencyKey(ctx context.Context, arg FindOrderByIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, findOrderByIdempotencyKey, arg.TenantID, arg.CustomerID, arg.IdempotencyKey)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCustomerOrderByCode = `-- name: GetCustomerOrderByCode :one
select id, tenant_id, customer_id, channel_id, external_order_ref, status, payment_status, fulfillment_type, pickup_at, production_start_at, production_date, shopping_cutoff_at, dp_due_at, balance_due_at, subtotal_idr, tax_idr, shipping_idr, total_idr, dp_required_idr, full_payment_required, terms_version, terms_accepted_at, idempotency_key, created_at, updated_at, code, notes, customer_name, customer_phone, customer_email from orders
where tenant_id = $1 and customer_id = $2 and code = $3
`

type GetCustomerOrderByCodeParams struct {
	TenantID   uuid.UUID
	CustomerID uuid.UUID
	Code       string
}

func (q *Queries) GetCustomerOrderByCode(ctx context.Context, arg GetCustomerOrderByCodeParams) (Order, error) {
	row := q.db.QueryRow(ctx, getCustomerOrderByCode, arg.TenantID, arg.CustomerID, arg.Code)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ChannelID,
		&i.ExternalOrderRef,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentType,
		&i.PickupAt,
		&i.ProductionStartAt,
		&i.ProductionDate,
		&i.ShoppingCutoffAt,
		&i.DpDueAt,
		&i.BalanceDueAt,
		&i.SubtotalIdr,
		&i.TaxIdr,
		&i.ShippingIdr,
		&i.TotalIdr,
		&i.DpRequiredIdr,
		&i.FullPaymentRequired,
		&i.TermsVersion,
		&i.TermsAcceptedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
		&i.Notes,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
select id, tenant_id, customer_id, channel_id, external_order_ref, status, payment_status, fulfillment_type, pickup_at, production_start_at, production_date, shopping_cutoff_at, dp_due_at, balance_due_at, subtotal_idr, tax_idr, shipping_idr, total_idr, dp_required_idr, full_payment_required, terms_version, terms_accepted_at, idempotency_key, created_at, updated_at, code, notes, customer_name, customer_phone, customer_email from orders
where tenant_id = $1 and id = $2
`

type GetOrderParams struct {
	TenantID uuid.UUID
	ID       uuid.UUID
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.TenantID, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CustomerID,
		&i.ChannelID,
		&i.ExternalOrderRef,
		&i.Status,
		&i.PaymentStatus,
		&i.FulfillmentType,
		&i.PickupAt,
		&i.ProductionStartAt,
		&i.ProductionDate,
		&i.ShoppingCutoffAt,
		&i.DpDueAt,
		&i.BalanceDueAt,
		&i.SubtotalIdr,
		&i.TaxIdr,
		&i.ShippingIdr,
		&i.TotalIdr,
		&i.DpRequiredIdr,
		&i.FullPaymentRequired,
		&i.TermsVersion,
		&i.TermsAcceptedAt,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Code,
		&i.Notes,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CustomerEmail,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :one
insert into orders (id, tenant_id, customer_id, channel_id, code, status, payment_status, fulfillment_type,
                    pickup_at, production_start_at, production_date, shopping_cutoff_at, dp_due_at, balance_due_at,
                    subtotal_idr, tax_idr, shipping_idr, total_idr, dp_required_idr, full_payment_required,
                    terms_version, terms_accepted_at, idempotency_key, notes,
                    customer_name, customer_phone, customer_email, created_at, updated_at)
select $1, $2, $3, c.id, $4, $5,
       $6, $7, $8, $9,
       $10, $11, $12, $13,
       $14, $15, $16, $17,
       $18, $19, $20, $21,
       $22, $23, $24, $25,
       $26, $21, $21
from channels c
where c.tenant_id = $2 and c.key = $27
on conflict (tenant_id, code) do nothing
returning id
`

type InsertOrderParams struct {
	ID                  uuid.UUID
	TenantID            uuid.UUID
	CustomerID          uuid.UUID
	Code                string
	Status              string
	PaymentStatus       string
	FulfillmentType     string
	PickupAt            time.Time
	ProductionStartAt   time.Time
	ProductionDate      pgtype.Date
	ShoppingCutoffAt    time.Time
	DpDueAt             time.Time
	BalanceDueAt        time.Time
	SubtotalIdr         int64
	TaxIdr              int64
	ShippingIdr         int64
	TotalIdr            int64
	DpRequiredIdr       int64
	FullPaymentRequired bool
	TermsVersion        string
	Now                 time.Time
	IdempotencyKey      uuid.UUID
	Notes               string
	CustomerName        string
	CustomerPhone       string
	CustomerEmail       *string
	ChannelKey          string
}

// Returns no row when the random code is already taken: the caller draws
// another, and the transaction goes on.
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertOrder,
		arg.ID,
		arg.TenantID,
		arg.CustomerID,
		arg.Code,
		arg.Status,
		arg.PaymentStatus,
		arg.FulfillmentType,
		arg.PickupAt,
		arg.ProductionStartAt,
		arg.ProductionDate,
		arg.ShoppingCutoffAt,
		arg.DpDueAt,
		arg.BalanceDueAt,
		arg.SubtotalIdr,
		arg.TaxIdr,
		arg.ShippingIdr,
		arg.TotalIdr,
		arg.DpRequiredIdr,
		arg.FullPaymentRequired,
		arg.TermsVersion,
		arg.Now,
		arg.IdempotencyKey,
		arg.Notes,
		arg.CustomerName,
		arg.CustomerPhone,
		arg.CustomerEmail,
		arg.ChannelKey,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
insert into order_items (tenant_id, order_id, variant_id, product_name, variant_name, quantity,
                         unit_price_idr, production_minutes, min_notice_hours)
values ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9)
`

type InsertOrderItemParams struct {
	TenantID          uuid.UUID
	OrderID           uuid.UUID
	VariantID         uuid.UUID
	ProductName       string
	VariantName       string
	Quantity          int32
	UnitPriceIdr      int64
	ProductionMinutes int32
	MinNoticeHours    int32
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.TenantID,
		arg.OrderID,
		arg.VariantID,
		arg.ProductName,
		arg.VariantName,
		arg.Quantity,
		arg.UnitPriceIdr,
		arg.ProductionMinutes,
		arg.MinNoticeHours,
	)
	return err
}

const listCustomerOrders = `-- name: ListCustomerOrders :many
select o.id, o.code, o.status, o.payment_status, o.pickup_at, o.total_idr, o.created_at,
       (select count(*) from order_items i where i.order_id = o.id)::int as item_count,
       coalesce((select i.product_name || ' ' || i.variant_name from order_items i
                 where i.order_id = o.id order by i.product_name, i.variant_name, i.id limit 1), '')::text as first_item
from orders o
where o.tenant_id = $1 and o.customer_id = $2
order by o.created_at desc, o.id
limit $3
`

type ListCustomerOrdersParams struct {
	TenantID   uuid.UUID
	CustomerID uuid.UUID
	MaxRows    int32
}

type ListCustomerOrdersRow struct {
	ID            uuid.UUID
	Code          string
	Status        string
	PaymentStatus string
	PickupAt      time.Time
	TotalIdr      int64
	CreatedAt     time.Time
	ItemCount     int32
	FirstItem     string
}

// A customer's orders, newest first, with what the list shows of the items.
func (q *Queries) ListCustomerOrders(ctx context.Context, arg ListCustomerOrdersParams) ([]ListCustomerOrdersRow, error) {
	rows, err := q.db.Query(ctx, listCustomerOrders, arg.TenantID, arg.CustomerID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerOrdersRow{}
	for rows.Next() {
		var i ListCustomerOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.PaymentStatus,
			&i.PickupAt,
			&i.TotalIdr,
			&i.CreatedAt,
			&i.ItemCount,
			&i.FirstItem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCustomerOrders = `-- name: LockCustomerOrders :exec
select pg_advisory_xact_lock(hashtextextended('orders:' || $1::text, 0))
`

// Serializes one customer's checkouts until the transaction ends, so the
// limit on unpaid orders and the idempotency check cannot race.
func (q *Queries) LockCustomerOrders(ctx context.Context, customerID string) error {
	_, err := q.db.Exec(ctx, lockCustomerOrders, customerID)
	return err
}

const orderItems = `-- name: OrderItems :many
select id, tenant_id, order_id, variant_id, product_name, variant_name, quantity, unit_price_idr, production_minutes, min_notice_hours from order_items
where tenant_id = $1 and order_id = $2
order by product_name, variant_name, id
`

type OrderItemsParams struct {
	TenantID uuid.UUID
	OrderID  uuid.UUID
}

func (q *Queries) OrderItems(ctx context.Context, arg OrderItemsParams) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, orderItems, arg.TenantID, arg.OrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderItem{}
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OrderID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Quantity,
			&i.UnitPriceIdr,
			&i.ProductionMinutes,
			&i.MinNoticeHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
